### PR TITLE
Attachment storage

### PR DESCRIPTION
**Pull request by Goury**
#### What's this Pull Request do?
Secure file storage, prefixes for stored files and autodeletion of files on attachment deletion

#### What has been changed?
- [x] Secure file storage: files can be stored at custom location because media/ is almost always is served by server and you might not want all your confidential attachments to be served for just everybody.
- [x] Prefixes of 24 random symbols for stored files because instead of filesystem email message can have multiple files with the same name attached. Original filename is saved and used on sending the message.
- [x] Autodeletion of files deleted or changed attachments, because you should not store confidential data. And you might not want to bloat your filesystem with obsolete files.

#### Any background context you want to provide?
- [ ] Somewhere in future I will make view def for downloading securely stored files for staff with such permission.

#### GitHub issues
#80

### CODE REVIEW

**Comment by Goury** [comment]
also there is a little flaw, I will fix it soon, please do not accept this request until then.

**Comment by Goury** [comment]
Should be better now

**Comment by dstegelman** [comment]
I'll need a few days to test this out and everything, thanks for the PR.

**Comment by Goury** [comment]
Tomorrow I have to go for few days, I'll be back by Monday.

**Pull request merged**
