### PR TITLE
Date of creation for model and admin

### PR DESCRIPTION
**Pull request by Goury**
#### What's this Pull Request do?
Date of message creation is now stored in database and shown to admin

#### What has been changed?
- [x] Date of message creation for model and admin. Because I want to have it.

#### GitHub issues

### CODE REVIEW

**Comment by dstegelman** [comment]
I think this migration got created out of order, its marked as 0004 and it should be 0003

**Comment by dstegelman** [comment]
Ahh i see, its because of this change https://github.com/dstegelman/django-mail-queue/pull/83

I'll merge that one first and then you can re-create this one so its in the correct order.

**Comment by Goury** [comment]
Okay

**Comment by dstegelman** [comment]
This branch needs updated with master and then the migrations re-created.

**Comment by Goury** [comment]
Sorry for the delay, emergency things happen, I (hope I) will update this branch somewhere on the next week.

**Comment by Goury** [comment]
For reason unbeknown to me this github won't update this PR T_T

**Pull request closed without merging**
