### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by Goury**
#### What's this Pull Request do?
Bumped version to 2.3.1 so pip knows this one is new.

#### What has been changed?
- [x] Version bump to 2.3.1.

#### GitHub issues

### CODE REVIEW

**Comment by dstegelman** [comment]
It will actually be 3.0.0 as the python 3 stuff has already been merged.

**Comment by Goury** [comment]
Okay. let it be 3.0.0

**Comment by unformatt** [comment]
This isn't deployed yet, right? I still get 2.2.2 from pip

https://pypi.python.org/pypi/django-mail-queue

**Comment by dstegelman** [comment]
That is correct, my plan is to make a release very soon.

**Pull request merged**
