### PR TITLE
Secure file storage, prefixes for stored files, autodeletion of files on attachment deletion, date of creation for model and admin, version bump

### PR DESCRIPTION
**Pull request by Goury**
#### What's this Pull Request do?
Secure file storage, prefixes for stored files, autodeletion of files on attachment deletion, date of creation for model and admin, version bump

#### What has been changed?
- [x] Secure file storage: files can be stored at custom location because media/ is almost always is server by server and you might not want all your confidential attachments to be served for just everybody.
- [x] Prefixes or 24 randim symbols for stored files because instead of filesystem email message can have multiple files with the same name attached.
- [x] Autodeletion of files deleted or changed attachments, because you should not store confidential data.
- [x] Date of message creation for model and admin. Because I want to have it.
- [x] Version bump. Because of reasons.

#### GitHub issues
#80

### CODE REVIEW

**Comment by dstegelman** [comment]
Couple things.

- I'd would have gathered this be broken up into multiple pull requests as adding the created date has nothing to do with attempting to hide file attachments.
- After the model change, no migration was added.
- This is falling pyflakes checks on travis.

**Comment by Goury** [comment]
Aww.. I can fix first two things but can you please point me to some manual for third one?

**Comment by dstegelman** [comment]
Not sure what you mean by manual, but you can check out the travis builds https://travis-ci.org/dstegelman/django-mail-queue/builds/159889755

**Comment by Goury** [comment]
/me gone working on multiplying pull requests by advanced branching

**Pull request closed without merging**
